#!/bin/bash

git filter-branch --env-filter '
    if test "$GIT_AUTHOR_EMAIL" = "oldMailAddress@provider.com"
    then
        GIT_AUTHOR_EMAIL=newMailAddress@provider.com
    fi
    if test "$GIT_COMMITTER_EMAIL" = "oldMailAddress@provider.com"
    then
        GIT_COMMITTER_EMAIL=newMailAddress@provider.com
    fi
' -- --all

git push --all origin --force

